# Generated by Django 4.2.1 on 2023-05-17 14:28

import django.core.validators
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail_color_panel.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('geomanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorlayer',
            name='render_layers',
            field=wagtail.fields.StreamField([('fill', wagtail.blocks.StructBlock([('filter', wagtail.blocks.CharBlock(label='filter', required=False)), ('maxzoom', wagtail.blocks.IntegerBlock(label='maxzoom', required=False)), ('minzoom', wagtail.blocks.IntegerBlock(label='minzoom', required=False)), ('paint', wagtail.blocks.StructBlock([('fill_antialias', wagtail.blocks.BooleanBlock(default=True, label='fill antialias', required=False)), ('fill_color', wagtail_color_panel.blocks.NativeColorBlock(default='#000000', label='fill color')), ('fill_opacity', wagtail.blocks.IntegerBlock(default=1, label='fill opacity', required=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])), ('fill_outline_color', wagtail_color_panel.blocks.NativeColorBlock(default='#000000', label='fill outline color'))]))], label='fill'))], blank=True, null=True, use_json_field=True, verbose_name='Render Layers'),
        ),
    ]
