# Generated by Django 4.2.1 on 2023-05-30 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geomanager', '0003_alter_dataset_category_alter_dataset_sub_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoManagerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('sector', models.CharField(max_length=255, verbose_name='Sector')),
                ('organization', models.CharField(max_length=255, verbose_name='Organization')),
                ('organization_type', models.CharField(max_length=255, verbose_name='Organization Type')),
                ('scale_of_operations', models.CharField(max_length=255, verbose_name='Scale of Operations')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('how_do_you_use', models.CharField(blank=True, max_length=255, null=True, verbose_name='How do you Use')),
                ('interests', models.CharField(blank=True, max_length=255, null=True, verbose_name='Interests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
