# Generated by Django 4.2.1 on 2023-05-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomanager', '0004_geomanageruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='geomanagersettings',
            name='gadm_version',
            field=models.CharField(choices=[('4.1', '4.1'), ('4.0', '4.0')], default='4.1', max_length=50, verbose_name='GADM Boundary Data Version'),
        ),
    ]
