# Generated by Django 4.2.1 on 2023-05-31 09:25

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geomanager', '0006_dataset_can_clip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimagelayer',
            name='analysis',
            field=wagtail.fields.StreamField([('analysis', wagtail.blocks.StructBlock([('point_analysis', wagtail.blocks.StructBlock([('enable_data_at_point', wagtail.blocks.BooleanBlock(help_text='Show Data at Point on Click', label='enable_data_at_point', required=False)), ('unit', wagtail.blocks.CharBlock(help_text='Data Unit', label='Unit', required=False))], label='Point Analysis Settings'))], label='Analysis'))], blank=True, null=True, use_json_field=True, verbose_name='Analysis'),
        ),
    ]
