# Generated by Django 4.1.10 on 2023-07-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomanager', '0007_remove_stationsettings_id_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationsettings',
            name='name_column',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
