# Generated by Django 4.2.1 on 2023-05-31 09:59

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geomanager', '0007_fileimagelayer_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimagelayer',
            name='analysis',
            field=wagtail.fields.StreamField([('point_analysis', wagtail.blocks.StructBlock([('instance_data_enabled', wagtail.blocks.BooleanBlock(label='Show data for point', required=False)), ('timeseries_data_enabled', wagtail.blocks.BooleanBlock(label='Show timeseries data for point', required=False)), ('unit', wagtail.blocks.CharBlock(label='Data unit', required=False))], label='Point Analysis')), ('area_analysis', wagtail.blocks.StructBlock([('instance_data_enabled', wagtail.blocks.BooleanBlock(label='Show data for area', required=False)), ('instance_value_type', wagtail.blocks.ChoiceBlock(choices=[('mean', 'Mean of pixel values'), ('sum', 'Sum of pixel values'), ('minmax', 'Minimum, Maximum pixel values'), ('minmeanmax', 'Minimum, Mean, Maximum pixel values')], help_text='The value type that should be displayed', label='Area value type')), ('timeseries_data_enabled', wagtail.blocks.BooleanBlock(label='Show timeseries data for area', required=False)), ('timeseries_aggregation_method', wagtail.blocks.ChoiceBlock(choices=[('mean', 'By Mean'), ('sum', 'By Sum')], help_text='How should the region data be aggregated ?', label='Area timeseries data aggregation Method')), ('unit', wagtail.blocks.CharBlock(label='Data unit', required=False))], label='Area Analysis'))], blank=True, null=True, use_json_field=True, verbose_name='Analysis'),
        ),
    ]
