# Generated by Django 4.2.1 on 2023-06-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomanager', '0009_geomanageruserprofile_alter_fileimagelayer_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geomanageruserprofile',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='geomanageruserprofile',
            name='interests',
            field=models.TextField(blank=True, null=True, verbose_name='Interests'),
        ),
        migrations.AlterField(
            model_name='geomanageruserprofile',
            name='organization_type',
            field=models.TextField(max_length=255, verbose_name='Organization Type'),
        ),
        migrations.AlterField(
            model_name='geomanageruserprofile',
            name='sector',
            field=models.TextField(verbose_name='Sector'),
        ),
    ]
