# Generated by Django 4.2.1 on 2023-06-02 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geomanager', '0010_alter_geomanageruserprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geomanageruserprofile',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='geomanageruserprofile',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geomanageruserprofile',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('adm_0', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adm 0')),
                ('adm_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adm 1')),
                ('adm_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adm 2')),
                ('adm_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adm 3')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('products', models.TextField(blank=True, null=True, verbose_name='Products')),
                ('geostore_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geomanager.geostore', verbose_name='Geostore Id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
