# Generated by Django 4.2.1 on 2023-06-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomanager', '0011_alter_geomanageruserprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaofinterest',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='Tags'),
        ),
    ]
