# Generated by Django 4.2.1 on 2023-06-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomanager', '0012_areaofinterest_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaofinterest',
            name='webhook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Webhook UrlÏ'),
        ),
    ]
