# Generated by Django 4.1.10 on 2023-08-01 13:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('geomanager', '0013_geomanagersettings_logo_external_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geomanagersettings',
            name='privacy_policy_page',
            field=models.ForeignKey(blank=True, help_text='MapViewer Privacy Policy Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Privacy Policy Page'),
        ),
        migrations.AddField(
            model_name='geomanagersettings',
            name='terms_of_service_page',
            field=models.ForeignKey(blank=True, help_text='MapViewer Terms of Service page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Terms of Service Page'),
        ),
        migrations.AlterField(
            model_name='geomanagersettings',
            name='logo_external_link',
            field=models.URLField(blank=True, help_text='Used if internal logo page not provided', max_length=255, null=True, verbose_name='Logo external link'),
        ),
        migrations.AlterField(
            model_name='geomanagersettings',
            name='logo_page',
            field=models.ForeignKey(blank=True, help_text='Internal page to navigate to on clicking the logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Logo page'),
        ),
        migrations.AlterField(
            model_name='geomanagersettings',
            name='navigation',
            field=wagtail.fields.StreamField([('menu_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(label='Label')), ('page', wagtail.blocks.PageChooserBlock(help_text='Internal page to navigate', label='Page', required=False)), ('external_link', wagtail.blocks.URLBlock(help_text='External link to navigate to. Used if internal page not provided', label='External Link', required=False))], max_num=8)))], blank=True, null=True, use_json_field=True),
        ),
    ]
