# Generated by Django 4.1.10 on 2024-01-26 17:13

from django.db import migrations, models
from treebeard.mp_tree import MP_Node

from geomanager.models.core import Category


def create_root(apps, schema_editor):
    # Create root category by default
    Category.objects.create(
        title="Root",
        path="0001",
        depth=1,
        numchild=0,
    )


def update_paths(apps, schema_editor):
    class Node(MP_Node):
        pass

    # get root node
    root = Category.get_first_root_node()

    # get all categories except root
    categories = Category.objects.all().exclude(pk=root.pk)

    # update existing categories to be children of root
    for i, category in enumerate(categories, 1):
        # assign path, as depth 2 child of root
        category.path = Node._get_path(root.path, 2, i)

    if categories:
        Category.objects.bulk_update(categories, ["path"])

    # update root children count
    root.numchild = categories.count()
    root.save()


def backwards(apps, schema_editor):
    """nothing to do"""


class Migration(migrations.Migration):
    dependencies = [
        ('geomanager', '0042_alter_dataset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='depth',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(default="", max_length=255),
        ),
        migrations.RunPython(create_root, backwards),
        migrations.RunPython(update_paths, backwards),
        migrations.AlterField(
            model_name='category',
            name='path',
            field=models.CharField(max_length=255, unique=True)
        ),
    ]
