# Generated by Django 4.1.10 on 2023-11-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_stationspage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StationsPage',
        ),
    ]
