# Generated by Django 4.1.10 on 2023-11-09 10:40

from django.db import migrations, models
import django.db.models.deletion
import geomanager.fields
import wagtail.contrib.routable_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0004_delete_stationspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='StationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.JSONField(blank=True, null=True)),
                ('geom_type', models.CharField(blank=True, max_length=100, null=True)),
                ('bounds', geomanager.fields.ListField(blank=True, max_length=256, null=True)),
                ('name_column', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
