# Generated by Django 4.2.1 on 2023-05-16 08:48

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='cautions',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='cautions'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='citation',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='citation'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='download_data',
            field=models.URLField(blank=True, null=True, verbose_name='download_data'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='frequency_of_update',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='frequency_of_update'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='function',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='function'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='geographic_coverage',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='geographic_coverage'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='learn_more',
            field=models.URLField(blank=True, null=True, verbose_name='learn_more'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='license',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='license'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='overview',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='overview'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='resolution',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='resolution'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='source',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subtitle'),
        ),
    ]
