# Generated by Django 4.2.1 on 2023-05-16 09:03

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0002_metadata_cautions_metadata_citation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='cautions',
            field=wagtail.fields.RichTextField(blank=True, help_text='What things should users be aware as they use and interpret this dataset', null=True, verbose_name='cautions'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='citation',
            field=wagtail.fields.RichTextField(blank=True, help_text='Scientific citation for this dataset if any. For example the citation for a scientific paper for the dataset', null=True, verbose_name='citation'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='download_data',
            field=models.URLField(blank=True, help_text='External link to where the source data can be found and downloaded', null=True, verbose_name='download_data'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='frequency_of_update',
            field=models.CharField(blank=True, help_text='How frequent is the dataset updated. For example daily, weekly, monthly etc', max_length=255, null=True, verbose_name='frequency_of_update'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='function',
            field=models.TextField(blank=True, help_text='Short summary of what the dataset shows', max_length=255, null=True, verbose_name='function'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='geographic_coverage',
            field=models.CharField(blank=True, help_text='The geographic coverage of the dataset. For example East Africa or Ethiopia or Africa', max_length=255, null=True, verbose_name='geographic_coverage'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='learn_more',
            field=models.URLField(blank=True, help_text='External link where more detail about the dataset can be found', null=True, verbose_name='learn_more'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='license',
            field=models.CharField(blank=True, help_text='Any licensing information for the dataset', max_length=255, null=True, verbose_name='license'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='overview',
            field=wagtail.fields.RichTextField(blank=True, help_text='Detail description of the dataset, including the methodology, references or any other relevant information', null=True, verbose_name='overview'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='resolution',
            field=models.CharField(blank=True, help_text='The Spatial resolution of the dataset, for example 10km by 10 km', max_length=255, null=True, verbose_name='resolution'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='source',
            field=models.CharField(blank=True, help_text='The source of the data where was it generated or produced', max_length=255, null=True, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='subtitle',
            field=models.CharField(blank=True, help_text='subtitle', max_length=255, null=True, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='title',
            field=models.CharField(help_text='Metadata title', max_length=255, verbose_name='title'),
        ),
    ]
