# Generated by Django 4.2.1 on 2023-05-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('layermanager', '0004_alter_category_title_alter_metadata_download_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layermanagersettings',
            name='country_iso',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True, verbose_name='country'),
        ),
    ]
