# Generated by Django 4.2.1 on 2023-05-16 12:39

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0005_layermanagersettings_country_iso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layermanagersettings',
            name='country_iso',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='country'),
        ),
    ]
