# Generated by Django 4.2.1 on 2023-05-16 12:54

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0006_alter_layermanagersettings_country_iso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layermanagersettings',
            name='country_iso',
            field=django_countries.fields.CountryField(default='KE', max_length=2, verbose_name='country'),
            preserve_default=False,
        ),
    ]
