# Generated by Django 4.2.1 on 2023-05-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layermanager', '0007_alter_layermanagersettings_country_iso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layermanagersettings',
            old_name='country_iso',
            new_name='country',
        ),
    ]
